apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  namespace: project
spec:
  selector:
    app: grpc-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081