apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sub-deployment
  namespace: project
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: redis-sub
  template:
    metadata:
      labels:
        app: redis-sub
    spec:
      containers:
        - name: redis-sub
          image: avilatorres/redis-sub:latest
