apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pub-deployment
  namespace: project
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: redis-pub
  template:
    metadata:
      labels:
        app: redis-pub
    spec:
      containers:
        - name: redis-pub
          image: dmomotic/redis-pub:latest